apiVersion: v1
kind: Pod
metadata:
    name: kube-controller-manager
    namespace: kube-system
spec:
    hostNetwork: true
    containers:
    - name: kube-controller-manager
      image: index.tenxcloud.com/google_containers/kube-controller-manager-ppc64le:v1.3.0
      command:
      - /usr/local/bin/kube-controller-manager
      - --master=http://172.16.11.244:8080
      - --leader-elect=true
