apiVersion: v1
kind: Pod
metadata:
    name: kube-proxy
    namespace: kube-system
spec:
    hostNetwork: true
    containers:
    - name: kube-proxy
      image: index.tenxcloud.com/google_containers/kube-proxy-ppc64le:v1.3.0
      command:
      - /usr/local/bin/kube-proxy
      - --master=http://172.16.11.244:8080
      - --proxy-mode=iptables
      securityContext:
        privileged: true

